CONFIG:
  DEFAULT:
    EXECUTION_ENVIRONMENT: HML
    HEADLESS: False # True or False
  PROD:
    BASE_URL: https://automationtest.shop
    BROWSER: chrome
    TIMEOUT:  15
  HML:
    BASE_URL: https://automationtest.shop/
    BROWSER: chrome
    TIMEOUT:  30
