name: Robot Framework

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        continue-on-error: true

        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'
        - name: Setup Chrome
          uses: browser-actions/setup-chrome@v1
          with:
            id: setup-chrome
        - run: |
            echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
            ${{ steps.setup-chrome.outputs.chrome-path }} --version
